### ISSUE TITLE
Does not work on 1.6.14 & php 7.0

### ISSUE THREAD

**Issue by sickboards** [ICEPAY/Prestashop#4]
Tested 2.2.0b4 on prestashop 1.6.1.4 and php 7.0
install does not give any errors but in the back office it says bad SQL query 
and fails. 
Had to roll back my server to php 5.6 :( :( :( in order to get it to work again.

A workaround is highly appreciated!

**Comment by sickboards** [comment]
Workaround: completely unistall the icepay module and reinstall (don't forget to update the url's in the icepay portal).
Fix would be having an upgrade sql script that updates the database tables as they have changed.

**Comment by tsygankov** [comment]
Hi @sickboards ,

Sorry for the late reply. We actually have two absolutely different versions of the ICEPAY payment module for Prestashop. The most stable version at the moment is 2.1.2, but compatibility with Prestashop >1.6.1.1 is not tested. This version is using SOAP gateway. 

Version 2.2.0 is a BETA version of the REST API module. 

We will add a migration script that will solve the module compatibility problems.
